import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:["300","400"]
});
const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight:["300","400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
    data-theme="light"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistInter.className} min-h-full flex flex-col`}>
        <Navbar></Navbar>
        <main className="">
    
        {children}
        </main>
        <Footer></Footer>        
        </body>
    </html>
  );
}
